openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8010
  description: Generated server url
paths:
  /api/tasks/{id}:
    get:
      tags:
      - task
      operationId: getTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      tags:
      - task
      operationId: putTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTask'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      tags:
      - task
      operationId: deleteTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/unpinned:
    put:
      tags:
      - task
      operationId: putTaskUnpinned
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/unpending:
    put:
      tags:
      - task
      operationId: putTaskUnpending
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/undone:
    put:
      tags:
      - task
      operationId: putTaskUndone
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/restore:
    put:
      tags:
      - task
      operationId: restoreTask
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/pinned:
    put:
      tags:
      - task
      operationId: putTaskPinned
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/pending:
    put:
      tags:
      - task
      operationId: putTaskPending
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks/{id}/done:
    put:
      tags:
      - task
      operationId: putTaskDone
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tags/{id}:
    get:
      tags:
      - tag
      operationId: getTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
    put:
      tags:
      - tag
      operationId: putTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTag'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
    delete:
      tags:
      - tag
      operationId: deleteTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tags/{id}/unarchived:
    put:
      tags:
      - tag
      operationId: putTagUnarchived
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tags/{id}/restore:
    put:
      tags:
      - tag
      operationId: restoreTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tags/{id}/archived:
    put:
      tags:
      - tag
      operationId: putTagArchived
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/groups/{id}:
    get:
      tags:
      - group
      operationId: getGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
    put:
      tags:
      - group
      operationId: putGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGroup'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
    delete:
      tags:
      - group
      operationId: deleteGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/groups/{id}/unarchived:
    put:
      tags:
      - group
      operationId: putGroupUnarchived
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/groups/{id}/restore:
    put:
      tags:
      - group
      operationId: restoreGroup
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/groups/{id}/archived:
    put:
      tags:
      - group
      operationId: putGroupArchived
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /api/tasks:
    get:
      tags:
      - task
      operationId: getTasks
      parameters:
      - name: status
        in: query
        required: false
        schema:
          type: string
          default: undone
      - name: deleted
        in: query
        required: false
        schema:
          type: boolean
          default: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
      - task
      operationId: postTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTask'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /api/tags:
    get:
      tags:
      - tag
      operationId: getTags
      parameters:
      - name: archived
        in: query
        required: false
        schema:
          type: boolean
          default: false
      - name: deleted
        in: query
        required: false
        schema:
          type: boolean
          default: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
    post:
      tags:
      - tag
      operationId: postTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTag'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
  /api/groups:
    get:
      tags:
      - group
      operationId: getGroups
      parameters:
      - name: archived
        in: query
        required: false
        schema:
          type: boolean
          default: false
      - name: deleted
        in: query
        required: false
        schema:
          type: boolean
          default: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
    post:
      tags:
      - group
      operationId: postGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestGroup'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
components:
  schemas:
    RequestTask:
      type: object
      properties:
        groupId:
          type: integer
          format: int32
        title:
          type: string
        description:
          type: string
        order:
          type: integer
          format: int32
          nullable: true
        dueDate:
          type: string
          nullable: true
        tags:
          type: array
          items:
            type: integer
            format: int32
        notificationTags:
          type: array
          items:
            type: string
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int32
        groupId:
          type: integer
          format: int32
        title:
          type: string
        description:
          type: string
        pending:
          type: boolean
        pinned:
          type: boolean
        order:
          type: integer
          format: int32
          nullable: true
        dueDate:
          type: string
          format: date-time
          nullable: true
        doneAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
          nullable: true
        tags:
          type: array
          items:
            type: integer
            format: int32
        notificationTags:
          type: array
          items:
            type: string
    RequestTag:
      type: object
      properties:
        name:
          type: string
        classification:
          type: string
          nullable: true
        mainColor:
          type: string
        borderColor:
          type: string
          nullable: true
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        classification:
          type: string
          nullable: true
        mainColor:
          type: string
        borderColor:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        archivedAt:
          type: string
          format: date-time
          nullable: true
        deletedAt:
          type: string
          format: date-time
          nullable: true
    RequestGroup:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        hasDueDate:
          type: string
          enum:
          - ALWAYS
          - OPTIONAL
          - "NO"
        classifiedBy:
          type: string
          nullable: true
        order:
          type: integer
          format: int32
          nullable: true
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        hasDueDate:
          type: string
          enum:
          - ALWAYS
          - OPTIONAL
          - "NO"
        classifiedBy:
          type: string
        order:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        archivedAt:
          type: string
          format: date-time
          nullable: true
        deletedAt:
          type: string
          format: date-time
          nullable: true
